api/urls.py
from django.urls import path, include

urlpatterns = [
    path('v1/', include('api.v1.urls')),
]

api/v1/cources/urls.py
from django.urls import path, include
from .views import CoursesListView, CoursesUpdate, CourseDelete, CourseCreate

app_name = 'course'

urlpatterns = [
    path('cource/list/', CoursesListView.as_view(), name='course_list'),
    path('cource/create/', CourseCreate.as_view(), name='cources_create'),
    path('cource/update/<int:pk>', CoursesUpdate.as_view(), name='cources_update'),
    path('course/delete/<int:pk>', CourseDelete.as_view(), name='course_delete'),
]

cources/urls.py
from django.urls import path
from . import views

app_name = 'cources'

urlpatterns = [
    path('/cource/list', views.CourceListView.as_view(), name='cource_list'),
    path('/cource/create', views.CourceCreateView.as_view(), name='cource_create'),
    path('/cource/update/<int:pk>', views.CourceUpdateView.as_view(), name='update_cource'),
    path('/cource/delete/<int:pk>', views.DeleteView, name='delete_cource'),
]

educational_centre/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from . import views

from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.authtoken')),
    path('auth/', include('djoser.urls.jwt')),
    path('', views.AuthericationView.as_view(), name='home'),
    path('user', include('users.urls')),
    path('cource', include('cources.urls')),
    path('event', include('events.urls')),
    path('mark', include('marks.urls')),
    path('api/', include('api.urls')),
    path('api/token/', TokenObtainPairView.as_view()),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    path('admin/', admin.site.urls),
    path('', include("Home.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

events/urls.py
from django.urls import path
from . import views

app_name = 'events'

urlpatterns = [
    path('/event/list', views.EventsListView.as_view(), name='event_list'),
    path('/event/create', views.CreateEventView, name='event_create'),
    path('/event/update/<int:pk>', views.UpdateEventView, name='event_update'),
    path('/event/delete/<int:pk>', views.EventDeleteView, name='event_delete'),
]

users/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'users'

urlpatterns = [
    path('/login', views.AuthericationView.as_view(), name='login'),
    path('/logout', views.UserLogoutView.as_view(), name='logout'),

    path('/myprofile', views.myprofile, name='myprofile'),
    path('/question', views.question, name='question'),

    path('/student/register', views.StudentRegisterView.as_view(), name='student_register'),
    path('/student/list', views.StudentListView.as_view(), name='student_list'),
    path('/student/profile', views.StudentProfile, name='student_profile'),
    path('/student/detail/<int:pk>', views.StudentDetailView.as_view(), name='student_detail'),
    path('/student/update/<int:pk>', views.StudentUpdateView.as_view(), name='student_update'),
    path('/student/delete/<int:pk>', views.StudentDeleteView, name='student_delete'),
    
    path('/leader/profile', views.LeaderProfile, name='leader_profile'),
    path('/my/users', views.UsersListView.as_view(), name='my_users'),
    path('/user/create', views.UserCreateView.as_view(), name='user_create'),
    path('/user/detail/<int:pk>', views.UserDetailView.as_view(), name='user_detail'),
    path('/user/update/<int:pk>', views.UserUpdadeView.as_view(), name='user_update'),
    path('/user/delete/<int:pk>', views.UserDeleteView, name='user_delete'),

    # path('/teacher/register', views.TeacherRegisterView.as_view(), name='teacher_register'),
    path('/teacher/register', views.TeacherRegisterView, name='teacher_register'),
    path('/teacher/list', views.TeacherListView.as_view(), name='teacher_list'),
    path('/teacher/profile', views.TeacherProfile, name='teacher_profile'),
    path('/teacher/detail/<int:pk>', views.TeacherDetailView.as_view(), name='teacher_detail'),
    path('/teacher/update/<int:pk>', views.TeacherUpdateView, name='teacher_update'),
    path('/teacher/delete/<int:pk>', views.TeacherDeleteView, name='teacher_delete'),
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cources/models.py
from django.db import models

class Courses(models.Model):
    name = models.CharField(max_length=150)
    description = models.CharField(max_length=250)
    amount_of_lessons = models.IntegerField()
    price = models.IntegerField(blank=True)

    def __str__(self):
        return self.name

cources/forms.py
from django import forms
from .models import Courses

class CourceCreateForm(forms.ModelForm):
    class Meta:
        model = Courses
        fields = '__all__'

api/v1/cources/views.py
from rest_framework import generics
from cources.models import Courses
from .serializers import CoursesListSerializer
from users.models import Teacher
from rest_framework.permissions import AllowAny
# from events.models import Events

class CoursesListView(generics.ListAPIView):
    model = Courses
    serializer_class = CoursesListSerializer

    def get_queryset(self):
        cources = Courses.objects.all()
        if self.request.GET.get('teacher'):
            teacher_id = self.request.GET.get('teacher')
            return Courses.objects.filter(teacher__id=teacher_id)
        else:
            return Courses.objects.all()

class CourseCreate(generics.CreateAPIView):
    queryset = Courses.objects.all()
    serializer_class = CoursesListSerializer
    permission_classes = [AllowAny]
        
class CoursesUpdate(generics.RetrieveUpdateDestroyAPIView):
    queryset = Courses.objects.all()
    serializer_class = CoursesListSerializer
    permission_classes = [AllowAny]


class CourseDelete(generics.DestroyAPIView):
    serializer_class = CoursesListSerializer
    permission_classes = [AllowAny]

cources/views.py
from django.shortcuts import render, redirect
from .models import Courses
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from .forms import CourceCreateForm
from django.urls import reverse_lazy
from django.urls import reverse

class CourceListView(ListView):
    model = Courses
    template_name = 'cources/cource_list.html'
    context_object_name = 'cources'



class CourceCreateView(CreateView):
    template_name = 'cources/create_cource.html'
    form_class = CourceCreateForm
    success_url = reverse_lazy('cources:cource_list')



class CourceUpdateView(UpdateView):
    model = Courses
    form_class = CourceCreateForm
    template_name = 'cources/course_update.html'
    success_url = reverse_lazy('cources:cource_list')


def DeleteView(request, pk):
    cource = Courses.objects.filter(pk=pk)
    cource.delete()

    return redirect(reverse('cources:cource_list'))

templates/cources/cource_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- basic -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <!-- mobile metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="viewport" content="initial-scale=1, maximum-scale=1">
  <!-- site metas -->
  <title>mind</title>
  <meta name="keywords" content="">
  <meta name="description" content="">
  <meta name="author" content="">
  <!-- fevicon -->
  <link rel="icon" href="{% static 'users/img/fevicon.png' %}" type="image/gif" />
  <!-- bootstrap css -->
  <link rel="stylesheet" href="{% static 'users/css/bootstrap.min.css' %}">
  <!-- style css -->
  <link rel="stylesheet" href="{% static 'users/css/style.css' %}">
  <!-- Responsive-->
  <link rel="stylesheet" href="{% static 'users/css/responsive.css' %}">
  <!-- Scrollbar Custom CSS -->
  <link rel="stylesheet" href="{% static 'users/css/jquery.mCustomScrollbar.min.css' %}">
  <!-- Tweaks for older IEs-->
  <link rel="stylesheet" href="{% static 'https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css' %}">
  <link rel="stylesheet"
    href="{% static 'https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css' %}" media="screen">
    <link rel="stylesheet" href="{% static 'cources/main.css' %}">
  <!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
</head>
<!-- body -->
{% if request.user.leader %}
  <body class="main-layout">
    <!-- loader  -->
    <div class="loader_bg">
      <div class="loader"><img src="{% static 'users/img/loading.gif" alt="#" /></div>
    </div>
    <!-- end loader -->
    <!-- header -->
    <header>
      <div class="header-top">
        <div class="header">
          <div class="container-fluid">
            <div class="row">
              <div class="col-xl-2 col-lg-4 col-md-4 col-sm-3 col logo_section">
                <div class="full">
                  <div class="center-desk">
                    <div class="logo">
                      <a href="index.html"><img src="{% static 'users/img/logo.png' %}" alt="#" /></a>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-xl-10 col-lg-8 col-md-8 col-sm-9">
                <div class="header_information">
                  <div class="menu-area">
                    <div class="limit-box">
                      <nav class="main-menu ">
                        <ul class="menu-area-main">
                          <li class="active"> <a href="{% url 'home' %}">Home</a> </li>
                          <li> <a href="{% url 'users:my_users' %}">Users</a> </li>
                          <li> <a href="{% url 'users:teacher_list' %}">Teacher list</a></li>
                          <li> <a href="{% url 'users:student_list' %}">Student list</a> </li>
                          <li> <a href="{% url 'events:event_list' %}">Events</a></li>
                        </ul>
                      </nav>
                    </div>
                  </div>

                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </header>
    <br><br>
    

    {% if update %}
    <h1 style="text-align:center;">Edit cource</h1>

    <div class="form-container">
      <form method="POST">
          {% csrf_token %}
          <div class="form-control">
              <p>Name:</p>{{ form.name }}
          </div><br>
          <div class="form-control">
              <p>Description:</p>{{ form.description }}
          </div><br>
          <div class="form-control">
              <p>Amount of lessons:</p>{{ form.amount_of_lessons }}
          </div><br>
          <div class="form-control">
              <p>Price:</p>{{ form.price }}
          </div><br>
          <button class="btn btn-primary" type="submit">Edit</button>
          <a href="{% url 'cources:cource_list' %}" class="btn btn-primary">Back</a>
      </form>
    </div>

    {% else %}
    <h1 style="text-align:center;">Cource list</h1>
    <div class="container">
      <a href="{% url 'cources:cource_create' %}" class="btn btn-primary mb-4">Create cource</a>
      {% for cource in cources %}
          <div class="alert alert-primary" role="alert">
              <p>Name: {{ cource.name  }}</p>
              <p>Description: {{ cource.description }}</p>
              <p>Amount of lessons: {{ cource.amount_of_lessons }}</p>
              <p>Price: {{ cource.price }} sum</p>
              <a href="{% url 'cources:update_cource' cource.id %}" class="edit">Edit</a>
              <a href="{% url 'cources:delete_cource' cource.id %}" class="delete">Delete</a> 
          </div>  
      {% endfor %}
    </div>

    {% endif %}
    
  {% else %}

  <body class="main-layout">
    <!-- loader  -->
    <div class="loader_bg">
      <div class="loader"><img src="{% static 'users/img/loading.gif" alt="#" /></div>
    </div>
    <!-- end loader -->
    <!-- header -->
    <header>
      <div class="header-top">
        <div class="header">
          <div class="container-fluid">
            <div class="row">
              <div class="col-xl-2 col-lg-4 col-md-4 col-sm-3 col logo_section">
                <div class="full">
                  <div class="center-desk">
                    <div class="logo">
                      <a href="index.html"><img src="{% static 'users/img/logo.png' %}" alt="#" /></a>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-xl-10 col-lg-8 col-md-8 col-sm-9">
                <div class="header_information">
                  <div class="menu-area">
                    <div class="limit-box">
                      <nav class="main-menu ">
                        <ul class="menu-area-main">
                        </ul>
                      </nav>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </header>
    <br><br>
  <h1 style="text-align:center;" class="mt-4">Sorry, you don't have permission!</h1>

  {% endif %}


  
  <!-- Javascript files-->
  <script src="{% static 'users/js/jquery.min.js' %}"></script>
  <script src="{% static 'users/js/popper.min.js' %}"></script>
  <script src="{% static 'users/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'users/js/jquery-3.0.0.min.js' %}"></script>
  <script src="{% static 'users/js/plugin.js' %}"></script>
  <!-- sidebar -->
  <script src="{% static 'users/js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
  <script src="{% static 'users/js/custom.js' %}"></script>
  <script src="{% static 'https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js' %}"></script>


  <script>
    // This example adds a marker to indicate the position of Bondi Beach in Sydney,
    // Australia.
    function initMap() {
      var map = new google.maps.Map(document.getElementById('map'), {
        zoom: 11,
        center: {
          lat: 40.645037,
          lng: -73.880224
        },
      });

      var image = 'images/maps-and-flags.png';
      var beachMarker = new google.maps.Marker({
        position: {
          lat: 40.645037,
          lng: -73.880224
        },
        map: map,
        icon: image
      });
    }
  </script>
  <!-- google map js -->
  <script
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA8eaHt9Dh5H57Zh0xVTqxVdBFCvFMqFjQ&callback=initMap"></script>
  <!-- end google map js -->

</body>

</html>

templates/cources/course_update.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- basic -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <!-- mobile metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="viewport" content="initial-scale=1, maximum-scale=1">
  <!-- site metas -->
  <title>mind</title>
  <meta name="keywords" content="">
  <meta name="description" content="">
  <meta name="author" content="">
  <!-- fevicon -->
  <link rel="icon" href="{% static 'users/img/fevicon.png' %}" type="image/gif" />
  <!-- bootstrap css -->
  <link rel="stylesheet" href="{% static 'users/css/bootstrap.min.css' %}">
  <!-- style css -->
  <link rel="stylesheet" href="{% static 'users/css/style.css' %}">
  <!-- Responsive-->
  <link rel="stylesheet" href="{% static 'users/css/responsive.css' %}">
  <!-- Scrollbar Custom CSS -->
  <link rel="stylesheet" href="{% static 'users/css/jquery.mCustomScrollbar.min.css' %}">
  <!-- Tweaks for older IEs-->
  <link rel="stylesheet" href="{% static 'https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css' %}">
  <link rel="stylesheet"
    href="{% static 'https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css' %}" media="screen">
    <link rel="stylesheet" href="{% static 'users/css/main.css' %}">
  <!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
</head>
<!-- body -->

<body class="main-layout">
  <!-- loader  -->
  <div class="loader_bg">
    <div class="loader"><img src="{% static 'users/img/loading.gif" alt="#" /></div>
  </div>
  <!-- end loader -->
  <!-- header -->
  <header>
    <div class="header-top">
      <div class="header">
        <div class="container-fluid">
          <div class="row">
            <div class="col-xl-2 col-lg-4 col-md-4 col-sm-3 col logo_section">
              <div class="full">
                <div class="center-desk">
                  <div class="logo">
                    <a href="index.html"><img src="{% static 'users/img/logo.png' %}" alt="#" /></a>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-xl-10 col-lg-8 col-md-8 col-sm-9">
              <div class="header_information">
                <div class="menu-area">
                  <div class="limit-box">
                    <nav class="main-menu ">
                      <ul class="menu-area-main">
                        <li class="active"> <a href="{% url 'home' %}">Home</a> </li>
                        <li> <a href="{% url 'users:my_users' %}">My users</a> </li>
                        <li> <a href="{% url 'users:student_list' %}">Student list</a> </li>
                        <li> <a href="{% url 'cources:cource_list' %}">Cources</a></li>
                        <li> <a href="{% url 'events:event_list' %}">Events</a></li>
                      </ul>
                    </nav>
                  </div>
                </div>

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>
  <br><br>
  <h1 style="text-align:center;">Course edit</h1>

  <!-- <div class="form-container">
    <form method="POST">
      {% csrf_token %}
      <p>User:</p>{{form.user}}<br>
      <p>Sex:</p>{{form.sex}}<br>
      <p>Birthday:</p>{{form.birthday}}<br>
      <p>Phone:</p>{{form.phone}}<br>
      <button class="btn btn-primary" type="submit">Submit</button>
    </form>
  </div> -->

  <div class="form-container">
    <div class="panel-body">
      <div class="form-group">
          <label for="name">Name</label>
          <input id="name" class="form-control" type="text" value=""/>
      </div>
      <div class="form-group">
          <label for="description">Description</label>
          <input id="description" class="form-control" type="text" value=""/>
      </div>
      <div class="form-group">
        <label for="amount_of_lessons">Amount of lessons</label>
        <input id="amount_of_lessons" class="form-control" type="number"/>
      </div>
      <div class="form-group">
        <label for="price">Price</label>
        <input id="price" class="form-control" type="number"/>
      </div>
      <button id="course_update_btn" class="btn btn-primary" onclick="course_update()" data-url="{% url 'course:cources_update' courses.id %}">Submit</button>
      <a href="{% url 'cources:cource_list' %}" class="btn btn-primary">Back</a>
    </div>
  </div>

  <script>

    function course_update() {

        let formData = new FormData();
        formData.append('name', document.getElementById("name").value);
        formData.append('description', document.getElementById("description").value);
        formData.append('amount_of_lessons', document.getElementById("amount_of_lessons").value);
        formData.append('price', document.getElementById("price").value);
        var url = $("#course_update_btn  ").data("url");

        $.ajax({
                headers: { "X-CSRFToken": "{{csrf_token}}" },
                url: url,
                processData: false,
                contentType: false,
                method: 'PATCH',
                data: formData,
                success: function (data) {
                    alert('успех!');
                },
                error: function (data) {
                    alert('Ошибка');
                }
            });
    }
</script>
  
  <!-- Javascript files-->
  <script src="{% static 'users/js/jquery.min.js' %}"></script>
  <script src="{% static 'users/js/popper.min.js' %}"></script>
  <script src="{% static 'users/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'users/js/jquery-3.0.0.min.js' %}"></script>
  <script src="{% static 'users/js/plugin.js' %}"></script>
  <!-- sidebar -->
  <script src="{% static 'users/js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
  <script src="{% static 'users/js/custom.js' %}"></script>
  <script src="{% static 'https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js' %}"></script>


  <script>
    // This example adds a marker to indicate the position of Bondi Beach in Sydney,
    // Australia.
    function initMap() {
      var map = new google.maps.Map(document.getElementById('map'), {
        zoom: 11,
        center: {
          lat: 40.645037,
          lng: -73.880224
        },
      });

      var image = 'images/maps-and-flags.png';
      var beachMarker = new google.maps.Marker({
        position: {
          lat: 40.645037,
          lng: -73.880224
        },
        map: map,
        icon: image
      });
    }
  </script>
  <!-- google map js -->
  <script
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA8eaHt9Dh5H57Zh0xVTqxVdBFCvFMqFjQ&callback=initMap"></script>
  <!-- end google map js -->

</body>

</html>

templates/cources/create_cource.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- basic -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- mobile metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <!-- site metas -->
    <title>mind</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- fevicon -->
    <link rel="icon" href="{% static 'users/img/fevicon.png' %}" type="image/gif" />
    <!-- bootstrap css -->
    <link rel="stylesheet" href="{% static 'users/css/bootstrap.min.css' %}">
    <!-- style css -->
    <link rel="stylesheet" href="{% static 'users/css/style.css' %}">
    <!-- Responsive-->
    <link rel="stylesheet" href="{% static 'users/css/responsive.css' %}">
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet" href="{% static 'users/css/jquery.mCustomScrollbar.min.css' %}">
    <!-- Tweaks for older IEs-->
    <link rel="stylesheet"
        href="{% static 'https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css' %}">
    <link rel="stylesheet"
        href="{% static 'https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css' %}"
        media="screen">
    <link rel="stylesheet" href="{% static 'users/css/main.css' %}">
    <!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
</head>
<!-- body -->

<body class="main-layout">
    <!-- loader  -->
    <div class="loader_bg">
        <div class="loader"><img src="{% static 'users/img/loading.gif" alt="#" /></div>
    </div>
    <!-- end loader -->
    <!-- header -->
    <header>
        <div class="header-top">
            <div class="header">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-xl-2 col-lg-4 col-md-4 col-sm-3 col logo_section">
                            <div class="full">
                                <div class="center-desk">
                                    <div class="logo">
                                        <a href="index.html"><img src="{% static 'users/img/logo.png' %}" alt="#" /></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xl-10 col-lg-8 col-md-8 col-sm-9">
                            <div class="header_information">
                                <div class="menu-area">
                                    <div class="limit-box">
                                        <nav class="main-menu ">
                                            <ul class="menu-area-main">
                                                <li class="active"> <a href="{% url 'home' %}">Home</a> </li>
                                                <li> <a href="{% url 'users:my_users' %}">My users</a> </li>
                                                <li> <a href="{% url 'users:teacher_list' %}">Teacher list</a></li>
                                                <li> <a href="{% url 'cources:cource_list' %}">Cources</a></li>
                                                <li> <a href="{% url 'events:event_list' %}">Events</a></li>
                                            </ul>
                                        </nav>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <br><br>
    <h1 style="text-align:center;">Create cource</h1>
    <!-- <div class="form-container">
        <form method="POST">
            {% csrf_token %}
            <div class="form-control">
                <p>Name:</p>{{ form.name }}
            </div><br>
            <div class="form-control">
                <p>Description:</p>{{ form.description }}
            </div><br>
            <div class="form-control">
                <p>Amount of lessons:</p>{{ form.amount_of_lessons }}
            </div><br>
            <div class="form-control">
                <p>Price:</p>{{ form.price }}
            </div><br>
            <button class="btn btn-primary" type="submit">Submit</button>
        </form>
    </div> -->

    <div class="form-container">
        <div class="panel-body">
          <div class="form-group">
              <label for="name">Name</label>
              <input id="name" class="form-control" type="text" value=""/>
          </div>
          <div class="form-group">
              <label for="description">Description</label>
              <input id="description" class="form-control" type="text" value=""/>
          </div>
          <div class="form-group">
            <label for="amount_of_lessons">Amount of lessons</label>
            <input id="amount_of_lessons" class="form-control" type="number"/>
          </div>
          <div class="form-group">
            <label for="price">Price</label>
            <input id="price" class="form-control" type="number"/>
          </div>
          <button id="course_create_btn" class="btn btn-primary" onclick="course_create()" data-url="{% url 'course:cources_create' %}">Submit</button>
          <a href="{% url 'cources:cource_list' %}" class="btn btn-primary">Back</a>
        </div>
      </div>

      <script>

        function course_create() {
    
            let formData = new FormData();
            formData.append('name', document.getElementById("name").value);
            formData.append('description', document.getElementById("description").value);
            formData.append('amount_of_lessons', document.getElementById("amount_of_lessons").value);
            formData.append('price', document.getElementById("price").value);
            var url = $("#course_create_btn  ").data("url");
    
            $.ajax({
                    headers: { "X-CSRFToken": "{{csrf_token}}" },
                    url: url,
                    processData: false,
                    contentType: false,
                    method: 'POST',
                    data: formData,
                    success: function (data) {
                        alert('успех!');
                    },
                    error: function (data) {
                        alert('Ошибка');
                    }
                });
        }
    </script>




    <!-- Javascript files-->
    <script src="{% static 'users/js/jquery.min.js' %}"></script>
    <script src="{% static 'users/js/popper.min.js' %}"></script>
    <script src="{% static 'users/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'users/js/jquery-3.0.0.min.js' %}"></script>
    <script src="{% static 'users/js/plugin.js' %}"></script>
    <!-- sidebar -->
    <script src="{% static 'users/js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
    <script src="{% static 'users/js/custom.js' %}"></script>
    <script src="{% static 'https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js' %}"></script>


    <script>
        // This example adds a marker to indicate the position of Bondi Beach in Sydney,
        // Australia.
        function initMap() {
            var map = new google.maps.Map(document.getElementById('map'), {
                zoom: 11,
                center: {
                    lat: 40.645037,
                    lng: -73.880224
                },
            });

            var image = 'images/maps-and-flags.png';
            var beachMarker = new google.maps.Marker({
                position: {
                    lat: 40.645037,
                    lng: -73.880224
                },
                map: map,
                icon: image
            });
        }
    </script>
    <!-- google map js -->
    <script
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA8eaHt9Dh5H57Zh0xVTqxVdBFCvFMqFjQ&callback=initMap"></script>
    <!-- end google map js -->

</body>

</html>