api/urls.py
from django.urls import path, include

urlpatterns = [
    path('v1/', include('api.v1.urls')),
]

api/v1/users/urls.py
from django.urls import path, include
from .views import LeaderView, TeachersListView, TeacherUpdateView, StudentListView, TeacherCreateView, TeacherPasswordUpdateView, StudentCreateView, StudentUpdateView, StudentGroupListView, StudentGroupCreateView, LoginView, MyTokenObtainPairView

app_name = 'user'

urlpatterns = [
    path('leader/list/', LeaderView.as_view(), name='leader'),

    path('student/list/', StudentListView.as_view(), name='student_list'),
    path('student/create', StudentCreateView.as_view(), name='student_create'),
    path('student/update/<int:pk>', StudentUpdateView.as_view(), name='student_update'),
    path('student/group_list/', StudentGroupListView.as_view(), name='student_group_list'),
    path('student/group_create/', StudentGroupCreateView.as_view(), name='student_group_create'),

    path('teacher/list/', TeachersListView.as_view(), name='teacher_list'),
    path('teacher/create', TeacherCreateView.as_view(), name='teacher_create'),
    path('teacher/update/password/<int:pk>', TeacherPasswordUpdateView.as_view(), name='teacher_update'),
    path('teacher/update/<int:pk>', TeacherUpdateView.as_view(), name='update_teacher'),
    # path('teacher/password_update/', TeacherPasswordUpdateView.as_view(), name='teacher_password_update'),

    path('login/', LoginView.as_view(), name='custom_login'),
    path('customjwt/', MyTokenObtainPairView.as_view(), name='customjwt'),
]   

cources/urls.py
from django.urls import path
from . import views

app_name = 'cources'

urlpatterns = [
    path('/cource/list', views.CourceListView.as_view(), name='cource_list'),
    path('/cource/create', views.CourceCreateView.as_view(), name='cource_create'),
    path('/cource/update/<int:pk>', views.CourceUpdateView.as_view(), name='update_cource'),
    path('/cource/delete/<int:pk>', views.DeleteView, name='delete_cource'),
]

educational_centre/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from . import views

from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.authtoken')),
    path('auth/', include('djoser.urls.jwt')),
    path('', views.AuthericationView.as_view(), name='home'),
    path('user', include('users.urls')),
    path('cource', include('cources.urls')),
    path('event', include('events.urls')),
    path('mark', include('marks.urls')),
    path('api/', include('api.urls')),
    path('api/token/', TokenObtainPairView.as_view()),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    path('admin/', admin.site.urls),
    path('', include("Home.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

events/urls.py
from django.urls import path
from . import views

app_name = 'events'

urlpatterns = [
    path('/event/list', views.EventsListView.as_view(), name='event_list'),
    path('/event/create', views.CreateEventView, name='event_create'),
    path('/event/update/<int:pk>', views.UpdateEventView, name='event_update'),
    path('/event/delete/<int:pk>', views.EventDeleteView, name='event_delete'),
]

users/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'users'

urlpatterns = [
    path('/login', views.AuthericationView.as_view(), name='login'),
    path('/logout', views.UserLogoutView.as_view(), name='logout'),

    path('/myprofile', views.myprofile, name='myprofile'),
    path('/question', views.question, name='question'),

    path('/student/register', views.StudentRegisterView.as_view(), name='student_register'),
    path('/student/list', views.StudentListView.as_view(), name='student_list'),
    path('/student/profile', views.StudentProfile, name='student_profile'),
    path('/student/detail/<int:pk>', views.StudentDetailView.as_view(), name='student_detail'),
    path('/student/update/<int:pk>', views.StudentUpdateView.as_view(), name='student_update'),
    path('/student/delete/<int:pk>', views.StudentDeleteView, name='student_delete'),
    
    path('/leader/profile', views.LeaderProfile, name='leader_profile'),
    path('/my/users', views.UsersListView.as_view(), name='my_users'),
    path('/user/create', views.UserCreateView.as_view(), name='user_create'),
    path('/user/detail/<int:pk>', views.UserDetailView.as_view(), name='user_detail'),
    path('/user/update/<int:pk>', views.UserUpdadeView.as_view(), name='user_update'),
    path('/user/delete/<int:pk>', views.UserDeleteView, name='user_delete'),

    # path('/teacher/register', views.TeacherRegisterView.as_view(), name='teacher_register'),
    path('/teacher/register', views.TeacherRegisterView, name='teacher_register'),
    path('/teacher/list', views.TeacherListView.as_view(), name='teacher_list'),
    path('/teacher/profile', views.TeacherProfile, name='teacher_profile'),
    path('/teacher/detail/<int:pk>', views.TeacherDetailView.as_view(), name='teacher_detail'),
    path('/teacher/update/<int:pk>', views.TeacherUpdateView, name='teacher_update'),
    path('/teacher/delete/<int:pk>', views.TeacherDeleteView, name='teacher_delete'),
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/forms.py
from django import forms
from django.forms import TextInput, Textarea, DateTimeInput, Select, PasswordInput
from .models import LeaderProfile, Teacher, Student
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm



class AuthUserForm(AuthenticationForm,forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'password')
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'



class TeacherForm(forms.ModelForm):
    username = forms.CharField(max_length=100) 
    password = forms.CharField() 
    class Meta:
        model = Teacher
        fields = ['username', 'password', 'cources','bio','experience','sex','birthday','phone']

    
    
        # widgets = {
        #     "cources": Select(attrs={
        #         'class': 'form-control',
        #     }),
        #     "bio": Textarea(attrs={
        #         'class': 'form-control',
        #         'placeholder': 'Bio'
        #     }),
        #     "experience": TextInput(attrs={
        #         'class': 'form-control',
        #         'placeholder': 'Experience'
        #     }),
        #     "sex": TextInput(attrs={
        #         'class': 'form-control',
        #         'placeholder': 'Sex'
        #     }),
        #     "birthday": DateTimeInput(attrs={
        #         'class': 'form-control',
        #         'placeholder': 'Birthday'
        #     }),
        #     "phone": TextInput(attrs={
        #         'class': 'form-control',
        #         'placeholder': 'Phone'
        #     }),
        # }


class StudentForm(forms.ModelForm):
    user = forms.ModelChoiceField(queryset=User.objects.all())
    class Meta:
        model = Student
        fields = ['user', 'sex','birthday','phone']


class UserCreateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']
    
    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

api/v1/users/views.py
from django.shortcuts import render
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework import generics, permissions
from rest_framework import settings
from rest_framework.permissions import BasePermission, IsAuthenticated, SAFE_METHODS, AllowAny


from users.models import LeaderProfile, Teacher, Student, StudentGroup
from events.models import Events
from cources.models import Courses
from .serializers import LeaderSerializer, TeacherListSerializer, StudentListSerializer, TeacherCreateSerializer, StudentCreateSerializer, StudentGroupListSerializer, StudentGroupCreateSerializer, MyTokenObtainPairSerializer
from .permissions import StudentUpdatePermission, TeacherUpdatePermissionClass, TeacherListPermission

from rest_framework_simplejwt.serializers import TokenObtainPairSerializer
from rest_framework_simplejwt.views import TokenObtainPairView


class LeaderView(generics.ListAPIView):
    queryset = LeaderProfile
    serializer_class = LeaderSerializer
    permission_class = [IsAuthenticated]


class TeachersListView(generics.ListAPIView):
    queryset = Teacher.objects.all()
    serializer_class = TeacherListSerializer
    permission_classes = [TeacherListPermission, IsAuthenticated]



class TeacherCreateView(generics.CreateAPIView):
    permission_class = [AllowAny]
    queryset = Teacher.objects.all()
    serializer_class = TeacherCreateSerializer
    


class TeacherPasswordUpdateView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Teacher.objects.all()
    serializer_class = TeacherCreateSerializer
    permission_classes = [TeacherUpdatePermissionClass, IsAuthenticated]


class TeacherUpdateView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Teacher.objects.all()
    serializer_class = TeacherCreateSerializer
    permission_classes = [AllowAny]


class TeacherAccountView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Teacher
    serializer_class = TeacherListSerializer


class StudentListView(generics.ListAPIView):
    queryset = Student.objects.all()
    serializer_class = StudentListSerializer
    permission_classes = [IsAuthenticated]

class StudentCreateView(generics.CreateAPIView):
    queryset = Student.objects.all()
    serializer_class = StudentCreateSerializer
    permission_classes = [AllowAny]


class StudentUpdateView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Student.objects.all()
    serializer_class = StudentCreateSerializer
    permission_classes = [AllowAny]


class StudentAccountView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Student.objects.all()
    permission_classes = StudentListSerializer

  

class StudentGroupListView(generics.ListAPIView):
    serializer_class = StudentGroupListSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        groups = StudentGroup.objects.all()
        if self.request.GET.get('teacher_of_group'):
            teacher = self.request.GET.get('teacher_of_group')
            return Student.objects.filter(StudentGroup__teacher=teacher).distinct()
        else:
            return StudentGroup.objects.all()


class StudentGroupCreateView(generics.CreateAPIView):
    queryset = StudentGroup.objects.all()
    serializer_class = StudentGroupCreateSerializer
    permission_classes = [IsAuthenticated]



class LoginView(TokenObtainPairView):
    serializer_class = MyTokenObtainPairSerializer


class MyTokenObtainPairView(TokenObtainPairView):
    serializer_class = MyTokenObtainPairSerializer

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import CreateView, ListView, DeleteView, UpdateView, TemplateView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.urls import reverse_lazy, reverse
from django.contrib.auth import authenticate, login
from .forms import AuthUserForm, TeacherForm, StudentForm, UserCreateForm
from .models import LeaderProfile, Teacher, Student
from cources.models import Courses


class AuthericationView(LoginView):
    template_name = 'users/login.html'
    form_class = AuthUserForm    
    
    def get_success_url(self):
        if hasattr(self.request.user, 'teacher'):
            success_url = reverse_lazy('users:teacher_profile')
        elif hasattr(self.request.user, 'student'):
            success_url = reverse_lazy('users:student_profile')
        elif hasattr(self.request.user, 'leader'):
            success_url = reverse_lazy('users:leader_profile')

        return success_url

    

# class RegistrationView(CreateView):
#     template_name = 'users/registration.html'
#     form_class = RegUserForm
#     success_url = reverse_lazy('users:question')
    
#     def form_valid(self, form):
#         form_valid = super().form_valid(form)
#         username = form.cleaned_data["username"]
#         password = form.cleaned_data["password"]
#         auth_user = authenticate(username=username,password=password)
#         login(self.request, auth_user)
#         return form_valid

class UserLogoutView(LogoutView):
    next_page = reverse_lazy('home')


def myprofile(request):
    return render(request, 'users/myprofile.html')


def question(request):
    return render(request, 'users/question.html')


# class TeacherRegisterView(TemplateView):
#     template_name = 'users/teacher_register.html'

def TeacherRegisterView(request):
    courses = Courses.objects.all()
    context = {
        'courses':courses,
    }
    return render(request, 'users/teacher_register.html',context)

    

class StudentRegisterView(CreateView):
    template_name = 'users/student_register.html'
    form_class = StudentForm
    success_url = reverse_lazy('users:leader_profile')


def StudentProfile(request):
    return render(request, 'users/student_profile.html')


def TeacherProfile(request):
    return render(request, 'users/teacher_profile.html')


def LeaderProfile(request):
    return render(request, 'users/leader_profile.html')
    

class UsersListView(ListView):
    model = User
    template_name = 'users/my_users.html'
    context_object_name = 'users'


class UserCreateView(CreateView):
    model = User
    form_class = UserCreateForm
    template_name = 'users/user_create.html'
    success_url = reverse_lazy('users:my_users')


class UserDetailView(DeleteView):
    model = User
    template_name = 'users/user_detail.html'
    context_object_name = 'users'


class UserUpdadeView(UpdateView):
    model = User
    form_class = UserCreateForm
    template_name = 'users/user_update.html'
    success_url = reverse_lazy('users:my_users')


def UserDeleteView(request, pk):
    user = User.objects.filter(pk=pk)
    user.delete()
    return redirect(reverse('users:my_users'))


class TeacherListView(ListView):
    model = Teacher
    template_name = 'users/teacher_list.html'
    context_object_name = 'teachers'


class TeacherDetailView(DeleteView):
    model = Teacher
    template_name = 'users/teacher_detail.html'
    context_object_name = 'teachers'
    


# class TeacherUpdateView(UpdateView):
#     model = Teacher
#     form_class = TeacherForm
#     template_name = 'users/teacher_update.html'
#     success_url = reverse_lazy('users:teacher_list')

def TeacherUpdateView(request, pk):
    courses = Courses.objects.all()

    context = {
        'courses': courses,
    }
    return render(request, 'users/teacher_update.html', context)


def TeacherDeleteView(request, pk):
    teacher = Teacher.objects.filter(pk=pk)
    teacher.delete()
    return redirect(reverse('users:teacher_list'))


class StudentListView(ListView):
    model = Student
    template_name = 'users/student_list.html'
    context_object_name = 'students'


class StudentDetailView(DeleteView):
    model = Student
    template_name = 'users/student_detail.html'
    context_object_name = 'students'


class StudentUpdateView(UpdateView):
    model = Student
    form_class = StudentForm
    template_name = 'users/student_update.html'
    success_url = reverse_lazy('users:student_list')


def StudentDeleteView(request, pk):
    student = Student.objects.filter(pk=pk)
    student.delete()
    return redirect(reverse('users:student_list'))

templates/users/my_users.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- basic -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <!-- mobile metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="viewport" content="initial-scale=1, maximum-scale=1">
  <!-- site metas -->
  <title>mind</title>
  <meta name="keywords" content="">
  <meta name="description" content="">
  <meta name="author" content="">
  <!-- fevicon -->
  <link rel="icon" href="{% static 'users/img/fevicon.png' %}" type="image/gif" />
  <!-- bootstrap css -->
  <link rel="stylesheet" href="{% static 'users/css/bootstrap.min.css' %}">
  <!-- style css -->
  <link rel="stylesheet" href="{% static 'users/css/style.css' %}">
  <!-- Responsive-->
  <link rel="stylesheet" href="{% static 'users/css/responsive.css' %}">
  <!-- Scrollbar Custom CSS -->
  <link rel="stylesheet" href="{% static 'users/css/jquery.mCustomScrollbar.min.css' %}">
  <!-- Tweaks for older IEs-->
  <link rel="stylesheet" href="{% static 'https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css' %}">
  <link rel="stylesheet"
    href="{% static 'https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css' %}" media="screen">
    <link rel="stylesheet" href="{% static 'users/css/main.css' %}">
  <!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
</head>
<!-- body -->
{% if request.user.leader %}
  <body class="main-layout">
    <!-- loader  -->
    <div class="loader_bg">
      <div class="loader"><img src="{% static 'users/img/loading.gif" alt="#" /></div>
    </div>
    <!-- end loader -->
    <!-- header -->
    <header>
      <div class="header-top">
        <div class="header">
          <div class="container-fluid">
            <div class="row">
              <div class="col-xl-2 col-lg-4 col-md-4 col-sm-3 col logo_section">
                <div class="full">
                  <div class="center-desk">
                    <div class="logo">
                      <a href="index.html"><img src="{% static 'users/img/logo.png' %}" alt="#" /></a>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-xl-10 col-lg-8 col-md-8 col-sm-9">
                <div class="header_information">
                  <div class="menu-area">
                    <div class="limit-box">
                      <nav class="main-menu ">
                        <ul class="menu-area-main">
                          <li class="active"> <a href="{% url 'home' %}">Home</a> </li>
                          <li> <a href="{% url 'users:teacher_list' %}">Teacher list</a></li>
                          <li> <a href="{% url 'users:student_list' %}">Student list</a> </li>
                          <li> <a href="{% url 'cources:cource_list' %}">Cources</a></li>
                          <li> <a href="{% url 'events:event_list' %}">Events</a></li>
                        </ul>
                      </nav>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </header>
    <br><br>
    <h1 style="text-align:center;">Users</h1>
    
    <div class="container">
      <a href="{% url 'users:user_create' %}" class="btn btn-primary mb-4">User create</a>
      {% for user in users %}
          <div class="alert alert-primary" role="alert">
              {{ user  }}
              <a href="{% url 'users:user_detail' user.id %}" class="float-right">view detail</a>
          </div>
      {% endfor %}
    </div>
  {% else %}
  <body class="main-layout">
    <!-- loader  -->
    <div class="loader_bg">
      <div class="loader"><img src="{% static 'users/img/loading.gif" alt="#" /></div>
    </div>
    <!-- end loader -->
    <!-- header -->
    <header>
      <div class="header-top">
        <div class="header">
          <div class="container-fluid">
            <div class="row">
              <div class="col-xl-2 col-lg-4 col-md-4 col-sm-3 col logo_section">
                <div class="full">
                  <div class="center-desk">
                    <div class="logo">
                      <a href="index.html"><img src="{% static 'users/img/logo.png' %}" alt="#" /></a>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-xl-10 col-lg-8 col-md-8 col-sm-9">
                <div class="header_information">
                  <div class="menu-area">
                    <div class="limit-box">
                      <nav class="main-menu ">
                        <ul class="menu-area-main">
                        </ul>
                      </nav>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </header>
    <br><br>
  <h1 style="text-align:center;" class="mt-4">Sorry, you don't have permission!</h1>

  {% endif %}


  <!-- Javascript files-->
  <script src="{% static 'users/js/jquery.min.js' %}"></script>
  <script src="{% static 'users/js/popper.min.js' %}"></script>
  <script src="{% static 'users/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'users/js/jquery-3.0.0.min.js' %}"></script>
  <script src="{% static 'users/js/plugin.js' %}"></script>
  <!-- sidebar -->
  <script src="{% static 'users/js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
  <script src="{% static 'users/js/custom.js' %}"></script>
  <script src="{% static 'https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js' %}"></script>


  <script>
    // This example adds a marker to indicate the position of Bondi Beach in Sydney,
    // Australia.
    function initMap() {
      var map = new google.maps.Map(document.getElementById('map'), {
        zoom: 11,
        center: {
          lat: 40.645037,
          lng: -73.880224
        },
      });

      var image = 'images/maps-and-flags.png';
      var beachMarker = new google.maps.Marker({
        position: {
          lat: 40.645037,
          lng: -73.880224
        },
        map: map,
        icon: image
      });
    }
  </script>
  <!-- google map js -->
  <script
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA8eaHt9Dh5H57Zh0xVTqxVdBFCvFMqFjQ&callback=initMap"></script>
  <!-- end google map js -->

</body>

</html>

templates/users/myprofile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>My profile!</h1>
</body>
</html>

templates/users/student_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- basic -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <!-- mobile metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="viewport" content="initial-scale=1, maximum-scale=1">
  <!-- site metas -->
  <title>mind</title>
  <meta name="keywords" content="">
  <meta name="description" content="">
  <meta name="author" content="">
  <!-- fevicon -->
  <link rel="icon" href="{% static 'users/img/fevicon.png' %}" type="image/gif" />
  <!-- bootstrap css -->
  <link rel="stylesheet" href="{% static 'users/css/bootstrap.min.css' %}">
  <!-- style css -->
  <link rel="stylesheet" href="{% static 'users/css/style.css' %}">
  <!-- Responsive-->
  <link rel="stylesheet" href="{% static 'users/css/responsive.css' %}">
  <!-- Scrollbar Custom CSS -->
  <link rel="stylesheet" href="{% static 'users/css/jquery.mCustomScrollbar.min.css' %}">
  <!-- Tweaks for older IEs-->
  <link rel="stylesheet" href="{% static 'https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css' %}">
  <link rel="stylesheet"
    href="{% static 'https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css' %}" media="screen">
    <link rel="stylesheet" href="{% static 'users/css/main.css' %}">
  <!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
</head>
<!-- body -->

<body class="main-layout">
  <!-- loader  -->
  <div class="loader_bg">
    <div class="loader"><img src="{% static 'users/img/loading.gif" alt="#" /></div>
  </div>
  <!-- end loader -->
  <!-- header -->
  <header>
    <div class="header-top">
      <div class="header">
        <div class="container-fluid">
          <div class="row">
            <div class="col-xl-2 col-lg-4 col-md-4 col-sm-3 col logo_section">
              <div class="full">
                <div class="center-desk">
                  <div class="logo">
                    <a href="index.html"><img src="{% static 'users/img/logo.png' %}" alt="#" /></a>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-xl-10 col-lg-8 col-md-8 col-sm-9">
              <div class="header_information">
                <div class="menu-area">
                  <div class="limit-box">
                    <nav class="main-menu ">
                      <ul class="menu-area-main">
                        <li class="active"> <a href="{% url 'home' %}">Home</a> </li>
                        <li> <a href="{% url 'users:my_users' %}">My users</a> </li>
                        <li> <a href="{% url 'users:student_list' %}">Student list</a> </li>
                        <li> <a href="{% url 'cources:cource_list' %}">Cources</a></li>
                        <li> <a href="{% url 'events:event_list' %}">Events</a></li>
                      </ul>
                    </nav>
                  </div>
                </div>

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>
  <br><br>
  <h1 style="text-align:center;">Student detail</h1>

  <div class="container">
        <div class="alert alert-primary" role="alert">
            <div class="form-control">
                <p>Name: {{ students }}</p> 
            </div><br>
            <div class="form-control">
                <p>Image: {{ students.image }}</p> 
            </div><br>
            <div class="form-control">
                <p>Sex: {{ students.sex }}</p> 
            </div><br>
            <div class="form-control">
                <p>Birthday: {{ students.birthday }}</p> 
            </div><br>
            <div class="form-control">
                <p>Phone: {{ students.phone }}</p>
            </div><br>
        </div>
        <a href="{% url 'users:student_update' students.id %}" class="btn btn-primary">Edit</a>
        <a href="{% url 'users:student_delete' students.id %}" class="btn btn-danger">Delete</a>
        <a href="{% url 'users:student_list' %}" class="btn btn-primary">Back</a>
  </div>

  
  <!-- Javascript files-->
  <script src="{% static 'users/js/jquery.min.js' %}"></script>
  <script src="{% static 'users/js/popper.min.js' %}"></script>
  <script src="{% static 'users/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'users/js/jquery-3.0.0.min.js' %}"></script>
  <script src="{% static 'users/js/plugin.js' %}"></script>
  <!-- sidebar -->
  <script src="{% static 'users/js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
  <script src="{% static 'users/js/custom.js' %}"></script>
  <script src="{% static 'https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js' %}"></script>


  <script>
    // This example adds a marker to indicate the position of Bondi Beach in Sydney,
    // Australia.
    function initMap() {
      var map = new google.maps.Map(document.getElementById('map'), {
        zoom: 11,
        center: {
          lat: 40.645037,
          lng: -73.880224
        },
      });

      var image = 'images/maps-and-flags.png';
      var beachMarker = new google.maps.Marker({
        position: {
          lat: 40.645037,
          lng: -73.880224
        },
        map: map,
        icon: image
      });
    }
  </script>
  <!-- google map js -->
  <script
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA8eaHt9Dh5H57Zh0xVTqxVdBFCvFMqFjQ&callback=initMap"></script>
  <!-- end google map js -->

</body>

</html>