api/urls.py
from django.urls import path, include

urlpatterns = [
    path('v1/', include('api.v1.urls')),
]

api/v1/events/urls.py
from django.urls import path, include
from .views import EventsListView, EventsUpdateView, EventCreateView

app_name = 'event'

urlpatterns = [
    path('event/list/', EventsListView.as_view(), name='events_list'),
    path('event/create/', EventCreateView.as_view(), name='event_create'),
    path('event/update/<int:pk>', EventsUpdateView.as_view(), name='event_update'),
]

cources/urls.py
from django.urls import path
from . import views

app_name = 'cources'

urlpatterns = [
    path('/cource/list', views.CourceListView.as_view(), name='cource_list'),
    path('/cource/create', views.CourceCreateView.as_view(), name='cource_create'),
    path('/cource/update/<int:pk>', views.CourceUpdateView.as_view(), name='update_cource'),
    path('/cource/delete/<int:pk>', views.DeleteView, name='delete_cource'),
]

educational_centre/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from . import views

from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.authtoken')),
    path('auth/', include('djoser.urls.jwt')),
    path('', views.AuthericationView.as_view(), name='home'),
    path('user', include('users.urls')),
    path('cource', include('cources.urls')),
    path('event', include('events.urls')),
    path('mark', include('marks.urls')),
    path('api/', include('api.urls')),
    path('api/token/', TokenObtainPairView.as_view()),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    path('admin/', admin.site.urls),
    path('', include("Home.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

events/urls.py
from django.urls import path
from . import views

app_name = 'events'

urlpatterns = [
    path('/event/list', views.EventsListView.as_view(), name='event_list'),
    path('/event/create', views.CreateEventView, name='event_create'),
    path('/event/update/<int:pk>', views.UpdateEventView, name='event_update'),
    path('/event/delete/<int:pk>', views.EventDeleteView, name='event_delete'),
]

users/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'users'

urlpatterns = [
    path('/login', views.AuthericationView.as_view(), name='login'),
    path('/logout', views.UserLogoutView.as_view(), name='logout'),

    path('/myprofile', views.myprofile, name='myprofile'),
    path('/question', views.question, name='question'),

    path('/student/register', views.StudentRegisterView.as_view(), name='student_register'),
    path('/student/list', views.StudentListView.as_view(), name='student_list'),
    path('/student/profile', views.StudentProfile, name='student_profile'),
    path('/student/detail/<int:pk>', views.StudentDetailView.as_view(), name='student_detail'),
    path('/student/update/<int:pk>', views.StudentUpdateView.as_view(), name='student_update'),
    path('/student/delete/<int:pk>', views.StudentDeleteView, name='student_delete'),
    
    path('/leader/profile', views.LeaderProfile, name='leader_profile'),
    path('/my/users', views.UsersListView.as_view(), name='my_users'),
    path('/user/create', views.UserCreateView.as_view(), name='user_create'),
    path('/user/detail/<int:pk>', views.UserDetailView.as_view(), name='user_detail'),
    path('/user/update/<int:pk>', views.UserUpdadeView.as_view(), name='user_update'),
    path('/user/delete/<int:pk>', views.UserDeleteView, name='user_delete'),

    # path('/teacher/register', views.TeacherRegisterView.as_view(), name='teacher_register'),
    path('/teacher/register', views.TeacherRegisterView, name='teacher_register'),
    path('/teacher/list', views.TeacherListView.as_view(), name='teacher_list'),
    path('/teacher/profile', views.TeacherProfile, name='teacher_profile'),
    path('/teacher/detail/<int:pk>', views.TeacherDetailView.as_view(), name='teacher_detail'),
    path('/teacher/update/<int:pk>', views.TeacherUpdateView, name='teacher_update'),
    path('/teacher/delete/<int:pk>', views.TeacherDeleteView, name='teacher_delete'),
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

events/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date
# from users.models import Teacher, Student
from cources.models import *


class Events(models.Model):
    day = models.DateField()
    start = models.TimeField()
    finish = models.TimeField()
    teacher = models.ForeignKey("users.Teacher", on_delete=models.CASCADE)
    student_group = models.ForeignKey("users.StudentGroup", on_delete=models.CASCADE)
    cource = models.ForeignKey(Courses, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.cource)

events/forms.py
from django import forms
from .models import Events

class EventForm(forms.ModelForm):
    class Meta:
        model = Events
        fields = '__all__'

api/v1/events/views.py
from rest_framework import generics, permissions
from events.models import Events
from .serializers import EventsListSerializer
from rest_framework.permissions import AllowAny



class EventsListView(generics.ListAPIView):
    queryset = Events.objects.all()
    serializer_class = EventsListSerializer

    
    def get_queryset(self):
        events = Events.objects.all()
        if self.request.GET.get('teacher'):
            teacher_id = self.request.GET.get('teacher')
            events = Events.objects.filter(teacher__id = teacher_id)
        else:
            return
            
            
        if self.request.GET.get('student_group'):
            student_group_id = self.request.GET.get('student_group')
            events = Events.objects.filter(student_group__id=student_group_id)

        return events

        
class EventCreateView(generics.CreateAPIView):
    permission_class = [AllowAny]
    queryset = Events.objects.all()
    serializer_class = EventsListSerializer

class EventsUpdateView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Events.objects.all()
    serializer_class = EventsListSerializer
    permission_classes = [AllowAny]

events/views.py
from django.shortcuts import render, redirect
from .models import Events
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from .forms  import EventForm
from django.urls import reverse_lazy, reverse
from users.models import Teacher, StudentGroup
from cources.models import Courses


class EventsListView(ListView):
    model = Events
    template_name = 'events/event_list.html'
    context_object_name = 'events'

# class EventCreateView(CreateView):
#     model = Events
#     template_name = 'events/event_create.html'
#     form_class = EventForm
#     success_url = reverse_lazy('events:event_list')

def CreateEventView(request):
    teachers = Teacher.objects.all()
    courses = Courses.objects.all()
    studentgroup = StudentGroup.objects.all()

    context = {
        'teachers':teachers,
        'courses':courses,
        'studentgroups':studentgroup,
    }
    return render(request, 'events/event_create.html', context)


def UpdateEventView(request, pk):
    teachers = Teacher.objects.all()
    courses = Courses.objects.all()
    studentgroup = StudentGroup.objects.all()

    context = {
        'teachers':teachers,
        'courses':courses,
        'studentgroups':studentgroup,
    }
    return render(request, 'events/event_update.html', context)

# class EventUpdateView(UpdateView):
#     model = Events
#     template_name = 'events/event_update.html'
#     form_class = EventForm
#     success_url = reverse_lazy('events:event_list')


def EventDeleteView(request, pk):
    event = Events.objects.filter(pk=pk)
    event.delete()
    return redirect(reverse('events:event_list'))

templates/events/event_create.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- basic -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <!-- mobile metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="viewport" content="initial-scale=1, maximum-scale=1">
  <!-- site metas -->
  <title>mind</title>
  <meta name="keywords" content="">
  <meta name="description" content="">
  <meta name="author" content="">
  <!-- fevicon -->
  <link rel="icon" href="{% static 'users/img/fevicon.png' %}" type="image/gif" />
  <!-- bootstrap css -->
  <link rel="stylesheet" href="{% static 'users/css/bootstrap.min.css' %}">
  <!-- style css -->
  <link rel="stylesheet" href="{% static 'users/css/style.css' %}">
  <!-- Responsive-->
  <link rel="stylesheet" href="{% static 'users/css/responsive.css' %}">
  <!-- Scrollbar Custom CSS -->
  <link rel="stylesheet" href="{% static 'users/css/jquery.mCustomScrollbar.min.css' %}">
  <!-- Tweaks for older IEs-->
  <link rel="stylesheet" href="{% static 'https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css' %}">
  <link rel="stylesheet"
    href="{% static 'https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css' %}" media="screen">
    <link rel="stylesheet" href="{% static 'users/css/main.css' %}">
  <!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
</head>
<!-- body -->

<body class="main-layout">
  <!-- loader  -->
  <div class="loader_bg">
    <div class="loader"><img src="{% static 'users/img/loading.gif" alt="#" /></div>
  </div>
  <!-- end loader -->
  <!-- header -->
  <header>
    <div class="header-top">
      <div class="header">
        <div class="container-fluid">
          <div class="row">
            <div class="col-xl-2 col-lg-4 col-md-4 col-sm-3 col logo_section">
              <div class="full">
                <div class="center-desk">
                  <div class="logo">
                    <a href="index.html"><img src="{% static 'users/img/logo.png' %}" alt="#" /></a>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-xl-10 col-lg-8 col-md-8 col-sm-9">
              <div class="header_information">
                <div class="menu-area">
                  <div class="limit-box">
                    <nav class="main-menu ">
                      <ul class="menu-area-main">
                        <li class="active"> <a href="{% url 'home' %}">Home</a> </li>
                        <li> <a href="{% url 'users:my_users' %}">My users</a> </li>
                        <li> <a href="{% url 'users:teacher_list' %}">Teacher list</a></li>
                        <li> <a href="{% url 'users:student_list' %}">Student list</a> </li>
                        <li> <a href="{% url 'cources:cource_list' %}">Cources</a></li>
                      </ul>
                    </nav>
                  </div>
                </div>

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>
  <br><br>
  <h1 style="text-align:center;">Event create</h1>

  <div class="form-container">
    <form method="POST">
      {% csrf_token %}
      <div class="panel-body">
        <div class="form-group">
          <label for="teacher">Teacher</label>
          <select class="form-control" id="teacher" name="teacher">
            {% for teacher in teachers %}
              <option value="{{ teacher.id }}">{{ teacher }}</option>
            {% endfor %}
          </select>
        </div><br><br>

        <div class="form-group">
            <label>Day</label>
            <input id="day" class="form-control" type="date" value=""/>
        </div>
        <div class="form-group">
          <label for="start">Start</label>
          <input id="start" class="form-control" type="time"/>
        </div>
        <div class="form-group">
          <label for="finish">Finish</label>
          <input id="finish" class="form-control" type="time"/>
        </div>
        <div class="form-group">
          <label for="student_group">Student group</label>
          <select class="form-control" id="student_group" name="student_group">
            {% for studentgroup in studentgroups %}
              <option value="{{ studentgroup.id }}">{{ studentgroup.name_of_group }}</option>
            {% endfor %}
          </select>
        </div>
        <div class="form-group">
          <label for="course">Cource</label>
          <select class="form-control" id="cource" name="course">
            {% for cource in courses %}
              <option value="{{ cource.id }}">{{ cource.name }}</option>
            {% endfor %}
          </select>
        </div><br><br><br>
        <button id="create_event_btn" class="btn btn-primary" onclick="create_event()" data-url="{% url 'event:event_create' %}">Submit</button>
        <a href="{% url 'events:event_list' %}" class="btn btn-primary">Back</a>
      </div>
    </form>
  </div>

  <script>

    function create_event() {

        let formData = new FormData();
        formData.append('teacher', document.getElementById("teacher").value);
        formData.append('day', document.getElementById("day").value);
        formData.append('start', document.getElementById("start").value);
        formData.append('finish', document.getElementById("finish").value);
        formData.append('student_group', document.getElementById("student_group").value);
        formData.append('cource', document.getElementById("cource").value);
        var url = $("#create_event_btn").data("url");

        $.ajax({
                headers: { "X-CSRFToken": "{{csrf_token}}" },
                url: url,
                processData: false,
                contentType: false,
                method: 'POST',
                data: formData,
                success: function (data) {
                    alert('успех!');
                },
                error: function (data) {
                    alert('Ошибка');
                }
            });
    }
</script>
  
  
  <!-- Javascript files-->
  <script src="{% static 'users/js/jquery.min.js' %}"></script>
  <script src="{% static 'users/js/popper.min.js' %}"></script>
  <script src="{% static 'users/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'users/js/jquery-3.0.0.min.js' %}"></script>
  <script src="{% static 'users/js/plugin.js' %}"></script>
  <!-- sidebar -->
  <script src="{% static 'users/js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
  <script src="{% static 'users/js/custom.js' %}"></script>
  <script src="{% static 'https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js' %}"></script>


  <script>
    // This example adds a marker to indicate the position of Bondi Beach in Sydney,
    // Australia.
    function initMap() {
      var map = new google.maps.Map(document.getElementById('map'), {
        zoom: 11,
        center: {
          lat: 40.645037,
          lng: -73.880224
        },
      });

      var image = 'images/maps-and-flags.png';
      var beachMarker = new google.maps.Marker({
        position: {
          lat: 40.645037,
          lng: -73.880224
        },
        map: map,
        icon: image
      });
    }
  </script>
  <!-- google map js -->
  <script
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA8eaHt9Dh5H57Zh0xVTqxVdBFCvFMqFjQ&callback=initMap"></script>
  <!-- end google map js -->

</body>

</html>

templates/events/event_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- basic -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <!-- mobile metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="viewport" content="initial-scale=1, maximum-scale=1">
  <!-- site metas -->
  <title>mind</title>
  <meta name="keywords" content="">
  <meta name="description" content="">
  <meta name="author" content="">
  <!-- fevicon -->
  <link rel="icon" href="{% static 'users/img/fevicon.png' %}" type="image/gif" />
  <!-- bootstrap css -->
  <link rel="stylesheet" href="{% static 'users/css/bootstrap.min.css' %}">
  <!-- style css -->
  <link rel="stylesheet" href="{% static 'users/css/style.css' %}">
  <!-- Responsive-->
  <link rel="stylesheet" href="{% static 'users/css/responsive.css' %}">
  <!-- Scrollbar Custom CSS -->
  <link rel="stylesheet" href="{% static 'users/css/jquery.mCustomScrollbar.min.css' %}">
  <!-- Tweaks for older IEs-->
  <link rel="stylesheet" href="{% static 'https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css' %}">
  <link rel="stylesheet"
    href="{% static 'https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css' %}" media="screen">
    <link rel="stylesheet" href="{% static 'users/css/main.css' %}">
  <!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
</head>
<!-- body -->
{% if request.user.leader %}
  <body class="main-layout">
    <!-- loader  -->
    <div class="loader_bg">
      <div class="loader"><img src="{% static 'users/img/loading.gif" alt="#" /></div>
    </div>
    <!-- end loader -->
    <!-- header -->
    <header>
      <div class="header-top">
        <div class="header">
          <div class="container-fluid">
            <div class="row">
              <div class="col-xl-2 col-lg-4 col-md-4 col-sm-3 col logo_section">
                <div class="full">
                  <div class="center-desk">
                    <div class="logo">
                      <a href="index.html"><img src="{% static 'users/img/logo.png' %}" alt="#" /></a>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-xl-10 col-lg-8 col-md-8 col-sm-9">
                <div class="header_information">
                  <div class="menu-area">
                    <div class="limit-box">
                      <nav class="main-menu ">
                        <ul class="menu-area-main">
                          <li class="active"> <a href="{% url 'home' %}">Home</a> </li>
                          <li> <a href="{% url 'users:my_users' %}">Users</a> </li>
                          <li> <a href="{% url 'users:teacher_list' %}">Teacher list</a></li>
                          <li> <a href="{% url 'users:student_list' %}">Student list</a> </li>
                          <li> <a href="{% url 'cources:cource_list' %}">Cources</a></li>
                        </ul>
                      </nav>
                    </div>
                  </div>

                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </header>
    <br><br>
    <h1 style="text-align:center;">Event list</h1>

    <div class="container">
      <a href="{% url 'events:event_create' %}" class="btn btn-primary mb-4">Create event</a>
      {% for event in events %}
          <div class="alert alert-primary" role="alert">
              <div class="form-control">
                  <p>№:{{ event.id  }}</p> 
              </div><br>
              <div class="form-control">
                  <p>Cource:{{ event.cource }}</p> 
              </div><br>
              <div class="form-control">
                  <p>Day:{{ event.day  }}</p> 
              </div><br>
              <div class="form-control">
                  <p>Time: {{ event.start  }} - {{ event.finish }}</p>
              </div><br>
              <div class="form-control">
                  <p>Teacher:{{ event.teacher  }}</p> 
              </div><br>
              <div class="form-control">
                  <p>Group:{{ event.student_group  }}</p> 
              </div><br><br>
              <a href="{% url 'events:event_update' event.id %}" class="btn btn-primary">Edit</a>
          <a href="{% url 'events:event_delete' event.id %}" class="btn btn-danger">Delete</a>
          </div>
      {% endfor %}
    </div>
  {% else %}
  <body class="main-layout">
    <!-- loader  -->
    <div class="loader_bg">
      <div class="loader"><img src="{% static 'users/img/loading.gif" alt="#" /></div>
    </div>
    <!-- end loader -->
    <!-- header -->
    <header>
      <div class="header-top">
        <div class="header">
          <div class="container-fluid">
            <div class="row">
              <div class="col-xl-2 col-lg-4 col-md-4 col-sm-3 col logo_section">
                <div class="full">
                  <div class="center-desk">
                    <div class="logo">
                      <a href="index.html"><img src="{% static 'users/img/logo.png' %}" alt="#" /></a>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-xl-10 col-lg-8 col-md-8 col-sm-9">
                <div class="header_information">
                  <div class="menu-area">
                    <div class="limit-box">
                      <nav class="main-menu ">
                        <ul class="menu-area-main">
                        </ul>
                      </nav>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </header>
    <br><br>
  <h1 style="text-align:center;" class="mt-4">Sorry, you don't have permission!</h1>

  {% endif %}

  
  <!-- Javascript files-->
  <script src="{% static 'users/js/jquery.min.js' %}"></script>
  <script src="{% static 'users/js/popper.min.js' %}"></script>
  <script src="{% static 'users/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'users/js/jquery-3.0.0.min.js' %}"></script>
  <script src="{% static 'users/js/plugin.js' %}"></script>
  <!-- sidebar -->
  <script src="{% static 'users/js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
  <script src="{% static 'users/js/custom.js' %}"></script>
  <script src="{% static 'https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js' %}"></script>


  <script>
    // This example adds a marker to indicate the position of Bondi Beach in Sydney,
    // Australia.
    function initMap() {
      var map = new google.maps.Map(document.getElementById('map'), {
        zoom: 11,
        center: {
          lat: 40.645037,
          lng: -73.880224
        },
      });

      var image = 'images/maps-and-flags.png';
      var beachMarker = new google.maps.Marker({
        position: {
          lat: 40.645037,
          lng: -73.880224
        },
        map: map,
        icon: image
      });
    }
  </script>
  <!-- google map js -->
  <script
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA8eaHt9Dh5H57Zh0xVTqxVdBFCvFMqFjQ&callback=initMap"></script>
  <!-- end google map js -->

</body>

</html>